### ISSUE TITLE
Could you share the rest of the code?

### ISSUE THREAD

**Issue by childe-wuhen** [geopanag/pandemic_tgnn#2]
Could you share the rest of the code? I can't find the code of MPNN_TL and the code of the function 'generate_graphs_by_day()' and 'generate_graphs_britain()' in the file 'utils'.

**Comment by geopanag** [comment]
These functions were made to manage the initial data, which we can not share due to the FB data license agreement. Instead I cropped the data such that we can share it and you can read it with generate_graphs_tmp. MPNN_TL is given by the metalearn.py.

**Comment by childe-wuhen** [comment]
Thanks a lot! But why don't you use the mean square error (MSE) or mean absolute error (MAE) to evaluate the model? by the way, how can I run "error_case_maps.R"? I know nothing about R language.

**Comment by childe-wuhen** [comment]
Thanks a lot! But why don't you use the mean square error (MSE) or mean absolute error (MAE) to evaluate the model? by the way, how can I run "error_case_maps.R"? I know nothing about R language.

**Comment by geopanag** [comment]
The training is done based on MSE (experiments.py line 30). The final predictions are evaluated on MAE (line 299) because it indicates the number of cases lost so it s more interpretable. The error_case_maps.R is used for the plotting so it is not required for  the method :) . I uploaded it because people were asking me about the map plots of the paper.

**Comment by catcatwang** [comment]
Hello, author. I still don't understand. I can't find generate_ graphs_ britain, generate_ graphs_ by_ Where are these two functions? How to call it？looking forward to your reply

**Comment by geopanag** [comment]
Hello, as I said above, these functions were used in the initial version with the FB data. Since I can not share these data I created an aggregated version that you can load with generate_graphs_tmp. That is why these functions are commented out.

**Comment by catcatwang** [comment]
Thank you very much for your reply. But I still can't debug the program successfully. I've changed the generate_ graphs_ TMP replaces generate_ graphs_ by_ Day, or display error. Do you know why, or can you release the final version?

**Comment by geopanag** [comment]
I have removed all instances and calls to generate_graphs_by_day from all scripts and fixed the path names. I tested experiments.py and metalearn and they are working. Please re-download the code and try again.

**Comment by catcatwang** [comment]
Thank you very much. I have successfully transferred the code

**Comment by catcatwang** [comment]
Hello, I'm sorry to disturb you again. I'd like to ask why i started training_ Loss and val_ Loss will be very big, reaching hundreds or even thousands,Is it because I use CPU instead of GPU?

**Comment by geopanag** [comment]
Hello, the error I print is the cumulative error. You have to divide it by the number of regions in the country to get the average per region. Also in the first test samples the train set is small (as noted in the paper) so you should expect the error to be big.
