### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by catcatwang** [geopanag/pandemic_tgnn#3]
Hello, author. I still don't understand. I can't find generate_ graphs_ britain, generate_ graphs_ by_ Where are these two functions? How to call it？looking forward to your reply

**Comment by geopanag** [comment]
Hello, as I said above, these functions were used in the initial version with the FB data. Since I can not share these data I created an aggregated version that you can load with generate_graphs_tmp. That is why these functions are commented out.

**Comment by wangzhengzhengkai** [comment]
Hello, I'm sorry to interrupt you again, I want to ask what is the biggest difference between tl_base and MPNN+TL in this paper?

**Comment by geopanag** [comment]
Hi. TL base is regularly trained in the concatenation of samples from four countries, and tested on the test set of the fourth. In the MAML based approach, we learn an initialization point from training task-specific models on samples from three countries. Than we train regularly on the train set of the fourth and test on its test set. 
Regarding questions pertaining to the methodology of the paper, please contact me on my email on the paper, as this is a repo for the code.

**Comment by wangzhengzhengkai** [comment]
I see. Thank you very much again
