### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by catcatwang** [geopanag/pandemic_tgnn#4]
Hello, did you refer to other people's literature for the TL_BASE method in the code, or did you propose it for this article? If you refer to other people's literature, which article is it? Looking forward to your recovery.

**Comment by geopanag** [comment]
Hello, the TL_BASE is a simple concatenation of all training countries' datasets and testing on the country left out. 
It is the most basic approach one would do, hence I am not aware of a paper that follows it for such a specific case as in our problem.

**Comment by catcatwang** [comment]
Thank you very much for your reply. I am very interested in your research. I have another question. I don't quite understand how you calculate the Pearson correlation coefficient. Could you please publish the relevant codes? Thank you again

**Comment by geopanag** [comment]
Thank you, I have described how to apply PC in the context of the dataset in the last paragraph at the end of the left column, third page in the arxiv version. 
You can use one of the several python implementations using the  time series of mobility and COVID cases of each region: 
https://stackabuse.com/calculating-pearson-correlation-coefficient-in-python-with-numpy/#:~:text=The%20Pearson%20Correlation%20coefficient%20can,values%20of%20a%20random%20variable

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.pearsonr.html

**Comment by catcatwang** [comment]
Thank you very much. I already know how to calculate Pearson correlation coefficient. I would like to ask if you have considered the impact of mobility between different countries in the multiple asynchronous stages of the epidemic?

**Comment by geopanag** [comment]
That is a good question. Since we lacked mobility data between regions of different countries, we didn't pursue inter-country correlations, but it's a very valid point for future work.

**Comment by catcatwang** [comment]
OK, thank you again
