### ISSUE TITLE
what is the function of skip tensor?

### ISSUE THREAD

**Issue by trainma** [geopanag/pandemic_tgnn#6]
hello author.I have read your code and found a skip tensor(models.py line-120).I dont know what the function of this skip tensor in the forward function.Hoping for your reply.

**Comment by geopanag** [comment]
Hello it is the initial features, reshaped such that we can concatenate them with the rnn representations (line 160). this is fed to the final layer and it is called a skip connection.

**Comment by trainma** [comment]
It just like the residual connection in resnet. Thank you very much.
