### ISSUE TITLE
How to choose the shift parameter to reproduce the result describes in the paper

### ISSUE THREAD

**Issue by kunruiZhu** [geopanag/pandemic_tgnn#9]
Hi George,

Thanks for the great repository. 

I am trying to reproduce the experiments results in the [paper](https://arxiv.org/abs/2009.08388) and run the experiments.py following the ```Run``` section in the REAME file.

However, shown in the figure below, when comparing the scores between the rule-based predictors(AVG/ AVG_WINDOW) whose output should be stable across different platforms, I notice that the average errors(AE) are closer to shift=1,3,6 instead of shift=2,6,13(equals to dt=3,7 and 14) reported in the paper. 

For example, shown in the figure below, the score for AVG predictor in England with the setting of _Up to next 3 Days_ shares the same AE 9.75 between the paper and the output from the code with shift=1 (highlighted with yellow), and for the AVG_WINDOW predictor in Italy, with the setting of _Up to next 14 Days_ shares similar AE 19.45 and 19.24 in the paper the output from shift=6 respectively.
On the contrary, in the paper, the MAE of AVG_WINDOW predictor in England with the _Up to next 14 Days_ setting is 8.54(highlighted  with orange) while the output from the code is 10.47 (highlighted with green box), which is quite different.

<img width="960" alt="截屏2022-10-18 22 14 24" src="https://user-images.githubusercontent.com/89620804/196455598-d8d76a3c-c611-4b6e-a9b7-8af108faf99e.png">

May i know the correct shift parameter to reproduce the average error reported in the paper?

Thanks,
Konroy

**Comment by geopanag** [comment]
Hello Konroy thanks a lot for your detailed comment. 
Correct me If I m wrong, but I think your results describe the error at the shift (as computed by the code).
The errors in the paper correspond to the average of these shifts e.g AVG_WINDOW up to 3 days in England means to take the average error for shift =0,1,2 i.e. ( 6.01+ 6.51+7.02)/3 = 6.513.

**Comment by kunruiZhu** [comment]
Got it, thanks for your explanation ;)
